language: go

go:
  - 1.13.x

before_install:
  - go get -t -v ./...

script:
  - go build -o ts-dns github.com/wolf-joe/ts-dns/cmd
  - go test -race ./... -gcflags=all=-l -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)